name: Create Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build the project
        run: make release

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: FourthTube.cia
          tag_name: build-${{ github.run_number }}
          body: "Automated pre-release based on commit ${{ github.sha }}"
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}